import { loader } from "fumadocs-core/source";
// Generated by `fumadocs-mdx` into apps/web/.source (gitignored).
import { docs } from "../../.source/server";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
